name: 'Install Perl, mod, deps'
description: 'Install Perl, module and dependencies'
inputs:
  os:
    description: Operating system
    required: true
  perl:
    description: Perl version
    required: true
  token:
    description: GitHub Token (needed for submodules)
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        token: ${{ inputs.token }}

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ inputs.perl }}

    - name: Show Perl version
      run: perl -V
      shell: bash

    - name: Install current cpanm
      run: cpanm App::cpanminus
      shell: bash

    - name: Install dependencies
      run: cpanm --installdeps .
      shell: bash

    - name: Show content of log files on Linux
      if: ${{ failure() && startsWith(inputs.os, 'ubuntu-') }}
      run: cat /home/runner/.cpanm/work/*/build.log
      shell: bash

    - name: Show content of log files on Mac
      if: ${{ failure() && startsWith(inputs.os, 'macos-') }}
      run: cat /Users/runner/.cpanm/work/*/build.log
      shell: bash

    - name: Show content of log files on Windows
      if: ${{ failure() && startsWith(inputs.os, 'windows-') }}
      run: cat C:/Users/RUNNER~1/.cpanm/work/*/build.log
      shell: cmd

    - name: Process Makefile.PL
      run: |
        perl Makefile.PL
        make
      shell: bash
